-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2016.4
-- Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity hsd_thr is
generic (
    C_S_AXI_BUS_A_ADDR_WIDTH : INTEGER := 5;
    C_S_AXI_BUS_A_DATA_WIDTH : INTEGER := 32 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    sync : IN STD_LOGIC;
    x0_V : IN STD_LOGIC_VECTOR (10 downto 0);
    x1_V : IN STD_LOGIC_VECTOR (10 downto 0);
    x2_V : IN STD_LOGIC_VECTOR (10 downto 0);
    x3_V : IN STD_LOGIC_VECTOR (10 downto 0);
    x4_V : IN STD_LOGIC_VECTOR (10 downto 0);
    x5_V : IN STD_LOGIC_VECTOR (10 downto 0);
    x6_V : IN STD_LOGIC_VECTOR (10 downto 0);
    x7_V : IN STD_LOGIC_VECTOR (10 downto 0);
    y0_V : OUT STD_LOGIC_VECTOR (15 downto 0);
    y1_V : OUT STD_LOGIC_VECTOR (15 downto 0);
    y2_V : OUT STD_LOGIC_VECTOR (15 downto 0);
    y3_V : OUT STD_LOGIC_VECTOR (15 downto 0);
    y4_V : OUT STD_LOGIC_VECTOR (15 downto 0);
    y5_V : OUT STD_LOGIC_VECTOR (15 downto 0);
    y6_V : OUT STD_LOGIC_VECTOR (15 downto 0);
    y7_V : OUT STD_LOGIC_VECTOR (15 downto 0);
    t0_V : OUT STD_LOGIC_VECTOR (13 downto 0);
    t0_V_ap_vld : OUT STD_LOGIC;
    t1_V : OUT STD_LOGIC_VECTOR (13 downto 0);
    t1_V_ap_vld : OUT STD_LOGIC;
    t2_V : OUT STD_LOGIC_VECTOR (13 downto 0);
    t2_V_ap_vld : OUT STD_LOGIC;
    t3_V : OUT STD_LOGIC_VECTOR (13 downto 0);
    t3_V_ap_vld : OUT STD_LOGIC;
    t4_V : OUT STD_LOGIC_VECTOR (13 downto 0);
    t4_V_ap_vld : OUT STD_LOGIC;
    t5_V : OUT STD_LOGIC_VECTOR (13 downto 0);
    t5_V_ap_vld : OUT STD_LOGIC;
    t6_V : OUT STD_LOGIC_VECTOR (13 downto 0);
    t6_V_ap_vld : OUT STD_LOGIC;
    t7_V : OUT STD_LOGIC_VECTOR (13 downto 0);
    t7_V_ap_vld : OUT STD_LOGIC;
    yv_V : OUT STD_LOGIC_VECTOR (3 downto 0);
    iy_V : OUT STD_LOGIC_VECTOR (2 downto 0);
    s_axi_BUS_A_AWVALID : IN STD_LOGIC;
    s_axi_BUS_A_AWREADY : OUT STD_LOGIC;
    s_axi_BUS_A_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_BUS_A_ADDR_WIDTH-1 downto 0);
    s_axi_BUS_A_WVALID : IN STD_LOGIC;
    s_axi_BUS_A_WREADY : OUT STD_LOGIC;
    s_axi_BUS_A_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_BUS_A_DATA_WIDTH-1 downto 0);
    s_axi_BUS_A_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_BUS_A_DATA_WIDTH/8-1 downto 0);
    s_axi_BUS_A_ARVALID : IN STD_LOGIC;
    s_axi_BUS_A_ARREADY : OUT STD_LOGIC;
    s_axi_BUS_A_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_BUS_A_ADDR_WIDTH-1 downto 0);
    s_axi_BUS_A_RVALID : OUT STD_LOGIC;
    s_axi_BUS_A_RREADY : IN STD_LOGIC;
    s_axi_BUS_A_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_BUS_A_DATA_WIDTH-1 downto 0);
    s_axi_BUS_A_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_BUS_A_BVALID : OUT STD_LOGIC;
    s_axi_BUS_A_BREADY : IN STD_LOGIC;
    s_axi_BUS_A_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0) );
end;


architecture behav of hsd_thr is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "hsd_thr,hls_ip_2016_4,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xcku085-flvb1760-2-e,HLS_INPUT_CLOCK=6.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=5.620000,HLS_SYN_LAT=3,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=274,HLS_SYN_LUT=824}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant C_S_AXI_DATA_WIDTH : INTEGER range 63 downto 0 := 20;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv4_2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_const_lv4_3 : STD_LOGIC_VECTOR (3 downto 0) := "0011";
    constant ap_const_lv14_1 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000001";
    constant ap_const_lv14_2 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000010";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv3_6 : STD_LOGIC_VECTOR (2 downto 0) := "110";
    constant ap_const_lv4_4 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_const_lv4_5 : STD_LOGIC_VECTOR (3 downto 0) := "0101";
    constant ap_const_lv4_6 : STD_LOGIC_VECTOR (3 downto 0) := "0110";
    constant ap_const_lv3_7 : STD_LOGIC_VECTOR (2 downto 0) := "111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0);
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal config_a : STD_LOGIC_VECTOR (31 downto 0);
    signal config_b : STD_LOGIC_VECTOR (31 downto 0);
    signal count : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal x7_V_read_reg_1370 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_pipeline_reg_pp0_iter1_x7_V_read_reg_1370 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_pipeline_reg_pp0_iter2_x7_V_read_reg_1370 : STD_LOGIC_VECTOR (10 downto 0);
    signal x6_V_read_reg_1375 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_pipeline_reg_pp0_iter1_x6_V_read_reg_1375 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_pipeline_reg_pp0_iter2_x6_V_read_reg_1375 : STD_LOGIC_VECTOR (10 downto 0);
    signal x5_V_read_reg_1380 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_pipeline_reg_pp0_iter1_x5_V_read_reg_1380 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_pipeline_reg_pp0_iter2_x5_V_read_reg_1380 : STD_LOGIC_VECTOR (10 downto 0);
    signal x4_V_read_reg_1385 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_pipeline_reg_pp0_iter1_x4_V_read_reg_1385 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_pipeline_reg_pp0_iter2_x4_V_read_reg_1385 : STD_LOGIC_VECTOR (10 downto 0);
    signal x3_V_read_reg_1390 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_pipeline_reg_pp0_iter1_x3_V_read_reg_1390 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_pipeline_reg_pp0_iter2_x3_V_read_reg_1390 : STD_LOGIC_VECTOR (10 downto 0);
    signal x2_V_read_reg_1395 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_pipeline_reg_pp0_iter1_x2_V_read_reg_1395 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_pipeline_reg_pp0_iter2_x2_V_read_reg_1395 : STD_LOGIC_VECTOR (10 downto 0);
    signal x1_V_read_reg_1400 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_pipeline_reg_pp0_iter1_x1_V_read_reg_1400 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_pipeline_reg_pp0_iter2_x1_V_read_reg_1400 : STD_LOGIC_VECTOR (10 downto 0);
    signal x0_V_read_reg_1405 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_pipeline_reg_pp0_iter1_x0_V_read_reg_1405 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_pipeline_reg_pp0_iter2_x0_V_read_reg_1405 : STD_LOGIC_VECTOR (10 downto 0);
    signal sync_read_reg_1410 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter1_sync_read_reg_1410 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter2_sync_read_reg_1410 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond_2_fu_420_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond_2_reg_1415 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter1_or_cond_2_reg_1415 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter2_or_cond_2_reg_1415 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond1_3_fu_442_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond1_3_reg_1419 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter1_or_cond1_3_reg_1419 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter2_or_cond1_3_reg_1419 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond2_4_fu_464_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond2_4_reg_1423 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter1_or_cond2_4_reg_1423 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter2_or_cond2_4_reg_1423 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond3_5_fu_486_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond3_5_reg_1427 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter1_or_cond3_5_reg_1427 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter2_or_cond3_5_reg_1427 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond4_6_fu_508_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond4_6_reg_1431 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter1_or_cond4_6_reg_1431 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter2_or_cond4_6_reg_1431 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond5_7_fu_530_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond5_7_reg_1435 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter1_or_cond5_7_reg_1435 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter2_or_cond5_7_reg_1435 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond6_8_fu_552_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond6_8_reg_1439 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter1_or_cond6_8_reg_1439 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter2_or_cond6_8_reg_1439 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond7_9_fu_574_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond7_9_reg_1443 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter1_or_cond7_9_reg_1443 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter2_or_cond7_9_reg_1443 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_14_fu_601_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_14_reg_1447 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter2_tmp_14_reg_1447 : STD_LOGIC_VECTOR (0 downto 0);
    signal g_2_cast_fu_607_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal g_9_fu_611_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal g_9_reg_1457 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_20_fu_617_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_20_reg_1463 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_reg_pp0_iter2_tmp_20_reg_1463 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_22_fu_623_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_22_reg_1469 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_28_fu_635_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_28_reg_1474 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_30_fu_641_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_30_reg_1481 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_31_fu_647_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_31_reg_1487 : STD_LOGIC_VECTOR (0 downto 0);
    signal g_11_fu_653_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal g_11_reg_1492 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_36_fu_660_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_36_reg_1499 : STD_LOGIC_VECTOR (0 downto 0);
    signal g_12_fu_666_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal g_12_reg_1506 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_45_fu_673_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_45_reg_1513 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_47_fu_679_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_47_reg_1520 : STD_LOGIC_VECTOR (0 downto 0);
    signal g_6_cast_fu_685_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal g_13_fu_689_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal g_13_reg_1531 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_55_fu_695_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_55_reg_1539 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_57_fu_701_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_57_reg_1546 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_58_fu_707_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_58_reg_1552 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_precharge_reg_pp0_iter0_g_reg_323 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_precharge_reg_pp0_iter1_g_reg_323 : STD_LOGIC_VECTOR (0 downto 0);
    signal g_7_fu_585_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_phi_precharge_reg_pp0_iter1_g_1_reg_336 : STD_LOGIC_VECTOR (1 downto 0);
    signal g_1_phi_fu_339_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal g_cast_fu_580_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal g_8_fu_594_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_phi_precharge_reg_pp0_iter1_g_2_reg_345 : STD_LOGIC_VECTOR (1 downto 0);
    signal g_2_phi_fu_348_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_phi_precharge_reg_pp0_iter1_g_3_reg_355 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_precharge_reg_pp0_iter2_g_3_reg_355 : STD_LOGIC_VECTOR (2 downto 0);
    signal g_10_fu_628_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_precharge_reg_pp0_iter2_g_4_reg_364 : STD_LOGIC_VECTOR (2 downto 0);
    signal g_4_phi_fu_367_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_precharge_reg_pp0_iter2_g_5_reg_374 : STD_LOGIC_VECTOR (2 downto 0);
    signal g_5_phi_fu_377_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_precharge_reg_pp0_iter2_g_6_reg_384 : STD_LOGIC_VECTOR (2 downto 0);
    signal g_6_phi_fu_387_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_phi_precharge_reg_pp0_iter2_p_Val2_1_reg_394 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_phi_precharge_reg_pp0_iter3_p_Val2_1_reg_394 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_s_fu_1357_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_fu_404_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_1_fu_408_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_fu_414_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_5_fu_426_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_6_fu_430_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_7_fu_436_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_9_fu_448_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_10_fu_452_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_11_fu_458_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_16_fu_470_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_17_fu_474_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_18_fu_480_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_24_fu_492_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_25_fu_496_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_26_fu_502_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_32_fu_514_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_33_fu_518_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_34_fu_524_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_41_fu_536_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_42_fu_540_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_43_fu_546_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_51_fu_558_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_52_fu_562_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_53_fu_568_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_13_fu_730_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal storemerge1_v_cast_c_fu_749_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_15_fu_745_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal sel_tmp1_fu_771_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp2_fu_776_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_23_fu_789_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp_v_fu_781_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal storemerge4_v_fu_794_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal storemerge4_v_cast_fu_802_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_21_fu_767_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal sel_tmp5_fu_821_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp10_demorgan_fu_831_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp_fu_835_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp3_fu_841_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp6_fu_826_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond_fu_854_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal newSel_cast_cast_fu_846_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal newSel_fu_860_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal newSel1_fu_867_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal newSel92_cast_fu_875_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_29_fu_817_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_38_fu_894_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp4_fu_909_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp19_demorgan_fu_920_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_39_fu_899_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp8_fu_925_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp26_demorgan_fu_937_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_40_fu_904_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp10_fu_943_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp11_fu_949_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp9_fu_931_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp7_fu_914_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond1_fu_963_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal newSel2_fu_955_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal newSel96_cast_cast_fu_969_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal or_cond2_fu_977_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond3_fu_990_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal newSel3_fu_982_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal newSel4_fu_996_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal newSel100_cast_fu_1004_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_37_fu_890_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal sel_tmp12_fu_1038_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp35_demorgan_fu_1048_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_48_fu_1023_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp14_fu_1052_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp42_demorgan_fu_1064_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_49_fu_1028_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp16_fu_1070_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp51_demorgan_fu_1082_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_50_fu_1033_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp18_fu_1088_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp19_fu_1094_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp17_fu_1076_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp15_fu_1058_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp13_fu_1043_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond4_fu_1108_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal newSel5_fu_1100_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal newSel104_cast_cast_fu_1114_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal or_cond5_fu_1122_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond6_fu_1143_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal newSel6_fu_1135_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal newSel106_cast_cast_fu_1128_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal newSel7_fu_1149_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal newSel110_cast_fu_1157_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_46_fu_1019_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal sel_tmp20_fu_1191_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp60_demorgan_fu_1201_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp22_fu_1205_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp67_demorgan_fu_1216_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_59_fu_1176_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp24_fu_1221_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp76_demorgan_fu_1233_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_60_fu_1181_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp26_fu_1239_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp87_demorgan_fu_1251_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_61_fu_1186_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp28_fu_1257_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp29_fu_1263_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp27_fu_1245_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp25_fu_1227_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp23_fu_1211_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp21_fu_1196_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond7_fu_1277_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal newSel8_fu_1269_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal newSel9_fu_1283_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal or_cond8_fu_1291_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond9_fu_1305_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal newSel116_cast_cast_fu_1297_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal or_cond10_fu_1318_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal newSel10_fu_1310_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal newSel11_fu_1324_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal newSel12_fu_1332_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal newSel122_cast_fu_1340_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_56_fu_1172_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_62_fu_1351_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_pipeline_idle_pp0 : STD_LOGIC;
    signal ap_condition_41 : BOOLEAN;
    signal ap_condition_276 : BOOLEAN;
    signal ap_condition_303 : BOOLEAN;

    component hsd_thr_BUS_A_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        config_a : OUT STD_LOGIC_VECTOR (31 downto 0);
        config_b : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    hsd_thr_BUS_A_s_axi_U : component hsd_thr_BUS_A_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_BUS_A_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_BUS_A_DATA_WIDTH)
    port map (
        AWVALID => s_axi_BUS_A_AWVALID,
        AWREADY => s_axi_BUS_A_AWREADY,
        AWADDR => s_axi_BUS_A_AWADDR,
        WVALID => s_axi_BUS_A_WVALID,
        WREADY => s_axi_BUS_A_WREADY,
        WDATA => s_axi_BUS_A_WDATA,
        WSTRB => s_axi_BUS_A_WSTRB,
        ARVALID => s_axi_BUS_A_ARVALID,
        ARREADY => s_axi_BUS_A_ARREADY,
        ARADDR => s_axi_BUS_A_ARADDR,
        RVALID => s_axi_BUS_A_RVALID,
        RREADY => s_axi_BUS_A_RREADY,
        RDATA => s_axi_BUS_A_RDATA,
        RRESP => s_axi_BUS_A_RRESP,
        BVALID => s_axi_BUS_A_BVALID,
        BREADY => s_axi_BUS_A_BREADY,
        BRESP => s_axi_BUS_A_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        config_a => config_a,
        config_b => config_b);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_CS_fsm_pp0_stage0 = ap_const_lv1_1) and not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if (not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0)))) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if (not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0)))) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_phi_precharge_reg_pp0_iter1_g_reg_323_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_condition_41 = ap_const_boolean_1)) then
                if (not((or_cond_2_fu_420_p2 = ap_const_lv1_0))) then 
                    ap_phi_precharge_reg_pp0_iter1_g_reg_323 <= ap_const_lv1_0;
                elsif ((or_cond_2_fu_420_p2 = ap_const_lv1_0)) then 
                    ap_phi_precharge_reg_pp0_iter1_g_reg_323 <= ap_const_lv1_1;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_precharge_reg_pp0_iter1_g_reg_323 <= ap_phi_precharge_reg_pp0_iter0_g_reg_323;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_precharge_reg_pp0_iter2_g_3_reg_355_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_condition_276 = ap_const_boolean_1)) then
                if (not((or_cond3_5_reg_1427 = ap_const_lv1_0))) then 
                    ap_phi_precharge_reg_pp0_iter2_g_3_reg_355 <= g_2_cast_fu_607_p1;
                elsif ((or_cond3_5_reg_1427 = ap_const_lv1_0)) then 
                    ap_phi_precharge_reg_pp0_iter2_g_3_reg_355 <= g_9_fu_611_p2;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_precharge_reg_pp0_iter2_g_3_reg_355 <= ap_phi_precharge_reg_pp0_iter1_g_3_reg_355;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_precharge_reg_pp0_iter3_p_Val2_1_reg_394_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_condition_303 = ap_const_boolean_1)) then
                if (not((ap_pipeline_reg_pp0_iter1_or_cond7_9_reg_1443 = ap_const_lv1_0))) then 
                    ap_phi_precharge_reg_pp0_iter3_p_Val2_1_reg_394 <= g_6_cast_fu_685_p1;
                elsif ((ap_pipeline_reg_pp0_iter1_or_cond7_9_reg_1443 = ap_const_lv1_0)) then 
                    ap_phi_precharge_reg_pp0_iter3_p_Val2_1_reg_394 <= g_13_fu_689_p2;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_precharge_reg_pp0_iter3_p_Val2_1_reg_394 <= ap_phi_precharge_reg_pp0_iter2_p_Val2_1_reg_394;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_CS_fsm_pp0_stage0 = ap_const_lv1_1) and not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))))) then
                ap_pipeline_reg_pp0_iter1_or_cond1_3_reg_1419 <= or_cond1_3_reg_1419;
                ap_pipeline_reg_pp0_iter1_or_cond2_4_reg_1423 <= or_cond2_4_reg_1423;
                ap_pipeline_reg_pp0_iter1_or_cond3_5_reg_1427 <= or_cond3_5_reg_1427;
                ap_pipeline_reg_pp0_iter1_or_cond4_6_reg_1431 <= or_cond4_6_reg_1431;
                ap_pipeline_reg_pp0_iter1_or_cond5_7_reg_1435 <= or_cond5_7_reg_1435;
                ap_pipeline_reg_pp0_iter1_or_cond6_8_reg_1439 <= or_cond6_8_reg_1439;
                ap_pipeline_reg_pp0_iter1_or_cond7_9_reg_1443 <= or_cond7_9_reg_1443;
                ap_pipeline_reg_pp0_iter1_or_cond_2_reg_1415 <= or_cond_2_reg_1415;
                ap_pipeline_reg_pp0_iter1_sync_read_reg_1410 <= sync_read_reg_1410;
                ap_pipeline_reg_pp0_iter1_x0_V_read_reg_1405 <= x0_V_read_reg_1405;
                ap_pipeline_reg_pp0_iter1_x1_V_read_reg_1400 <= x1_V_read_reg_1400;
                ap_pipeline_reg_pp0_iter1_x2_V_read_reg_1395 <= x2_V_read_reg_1395;
                ap_pipeline_reg_pp0_iter1_x3_V_read_reg_1390 <= x3_V_read_reg_1390;
                ap_pipeline_reg_pp0_iter1_x4_V_read_reg_1385 <= x4_V_read_reg_1385;
                ap_pipeline_reg_pp0_iter1_x5_V_read_reg_1380 <= x5_V_read_reg_1380;
                ap_pipeline_reg_pp0_iter1_x6_V_read_reg_1375 <= x6_V_read_reg_1375;
                ap_pipeline_reg_pp0_iter1_x7_V_read_reg_1370 <= x7_V_read_reg_1370;
                or_cond1_3_reg_1419 <= or_cond1_3_fu_442_p2;
                or_cond2_4_reg_1423 <= or_cond2_4_fu_464_p2;
                or_cond3_5_reg_1427 <= or_cond3_5_fu_486_p2;
                or_cond4_6_reg_1431 <= or_cond4_6_fu_508_p2;
                or_cond5_7_reg_1435 <= or_cond5_7_fu_530_p2;
                or_cond6_8_reg_1439 <= or_cond6_8_fu_552_p2;
                or_cond7_9_reg_1443 <= or_cond7_9_fu_574_p2;
                or_cond_2_reg_1415 <= or_cond_2_fu_420_p2;
                sync_read_reg_1410 <= (0=>sync, others=>'-');
                x0_V_read_reg_1405 <= x0_V;
                x1_V_read_reg_1400 <= x1_V;
                x2_V_read_reg_1395 <= x2_V;
                x3_V_read_reg_1390 <= x3_V;
                x4_V_read_reg_1385 <= x4_V;
                x5_V_read_reg_1380 <= x5_V;
                x6_V_read_reg_1375 <= x6_V;
                x7_V_read_reg_1370 <= x7_V;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0)))) then
                ap_pipeline_reg_pp0_iter2_or_cond1_3_reg_1419 <= ap_pipeline_reg_pp0_iter1_or_cond1_3_reg_1419;
                ap_pipeline_reg_pp0_iter2_or_cond2_4_reg_1423 <= ap_pipeline_reg_pp0_iter1_or_cond2_4_reg_1423;
                ap_pipeline_reg_pp0_iter2_or_cond3_5_reg_1427 <= ap_pipeline_reg_pp0_iter1_or_cond3_5_reg_1427;
                ap_pipeline_reg_pp0_iter2_or_cond4_6_reg_1431 <= ap_pipeline_reg_pp0_iter1_or_cond4_6_reg_1431;
                ap_pipeline_reg_pp0_iter2_or_cond5_7_reg_1435 <= ap_pipeline_reg_pp0_iter1_or_cond5_7_reg_1435;
                ap_pipeline_reg_pp0_iter2_or_cond6_8_reg_1439 <= ap_pipeline_reg_pp0_iter1_or_cond6_8_reg_1439;
                ap_pipeline_reg_pp0_iter2_or_cond7_9_reg_1443 <= ap_pipeline_reg_pp0_iter1_or_cond7_9_reg_1443;
                ap_pipeline_reg_pp0_iter2_or_cond_2_reg_1415 <= ap_pipeline_reg_pp0_iter1_or_cond_2_reg_1415;
                ap_pipeline_reg_pp0_iter2_sync_read_reg_1410 <= ap_pipeline_reg_pp0_iter1_sync_read_reg_1410;
                ap_pipeline_reg_pp0_iter2_tmp_14_reg_1447 <= tmp_14_reg_1447;
                ap_pipeline_reg_pp0_iter2_tmp_20_reg_1463 <= tmp_20_reg_1463;
                ap_pipeline_reg_pp0_iter2_x0_V_read_reg_1405 <= ap_pipeline_reg_pp0_iter1_x0_V_read_reg_1405;
                ap_pipeline_reg_pp0_iter2_x1_V_read_reg_1400 <= ap_pipeline_reg_pp0_iter1_x1_V_read_reg_1400;
                ap_pipeline_reg_pp0_iter2_x2_V_read_reg_1395 <= ap_pipeline_reg_pp0_iter1_x2_V_read_reg_1395;
                ap_pipeline_reg_pp0_iter2_x3_V_read_reg_1390 <= ap_pipeline_reg_pp0_iter1_x3_V_read_reg_1390;
                ap_pipeline_reg_pp0_iter2_x4_V_read_reg_1385 <= ap_pipeline_reg_pp0_iter1_x4_V_read_reg_1385;
                ap_pipeline_reg_pp0_iter2_x5_V_read_reg_1380 <= ap_pipeline_reg_pp0_iter1_x5_V_read_reg_1380;
                ap_pipeline_reg_pp0_iter2_x6_V_read_reg_1375 <= ap_pipeline_reg_pp0_iter1_x6_V_read_reg_1375;
                ap_pipeline_reg_pp0_iter2_x7_V_read_reg_1370 <= ap_pipeline_reg_pp0_iter1_x7_V_read_reg_1370;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_enable_reg_pp0_iter3))) then
                count <= p_s_fu_1357_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))) and (ap_pipeline_reg_pp0_iter1_or_cond5_7_reg_1435 = ap_const_lv1_0))) then
                g_11_reg_1492 <= g_11_fu_653_p2;
                tmp_36_reg_1499 <= tmp_36_fu_660_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))) and (ap_pipeline_reg_pp0_iter1_or_cond6_8_reg_1439 = ap_const_lv1_0))) then
                g_12_reg_1506 <= g_12_fu_666_p2;
                tmp_45_reg_1513 <= tmp_45_fu_673_p2;
                tmp_47_reg_1520 <= tmp_47_fu_679_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))) and (ap_pipeline_reg_pp0_iter1_or_cond7_9_reg_1443 = ap_const_lv1_0))) then
                g_13_reg_1531 <= g_13_fu_689_p2;
                tmp_55_reg_1539 <= tmp_55_fu_695_p2;
                tmp_57_reg_1546 <= tmp_57_fu_701_p2;
                tmp_58_reg_1552 <= tmp_58_fu_707_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_CS_fsm_pp0_stage0 = ap_const_lv1_1) and not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))) and (or_cond3_5_reg_1427 = ap_const_lv1_0))) then
                g_9_reg_1457 <= g_9_fu_611_p2;
                tmp_20_reg_1463 <= tmp_20_fu_617_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_CS_fsm_pp0_stage0 = ap_const_lv1_1) and not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))) and (or_cond2_4_reg_1423 = ap_const_lv1_0))) then
                tmp_14_reg_1447 <= tmp_14_fu_601_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))) and (ap_pipeline_reg_pp0_iter1_or_cond3_5_reg_1427 = ap_const_lv1_0))) then
                tmp_22_reg_1469 <= tmp_22_fu_623_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))) and (ap_pipeline_reg_pp0_iter1_or_cond4_6_reg_1431 = ap_const_lv1_0))) then
                tmp_28_reg_1474 <= tmp_28_fu_635_p2;
                tmp_30_reg_1481 <= tmp_30_fu_641_p2;
                tmp_31_reg_1487 <= tmp_31_fu_647_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_enable_reg_pp0_iter0, ap_pipeline_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0 downto 0);

    ap_condition_276_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
                ap_condition_276 <= ((ap_CS_fsm_pp0_stage0 = ap_const_lv1_1) and not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_enable_reg_pp0_iter1));
    end process;


    ap_condition_303_assign_proc : process(ap_start, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter2)
    begin
                ap_condition_303 <= (not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_enable_reg_pp0_iter2));
    end process;


    ap_condition_41_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0)
    begin
                ap_condition_41 <= ((ap_CS_fsm_pp0_stage0 = ap_const_lv1_1) and (ap_const_logic_1 = ap_enable_reg_pp0_iter0) and not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))));
    end process;


    ap_done_assign_proc : process(ap_start, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter3)
    begin
        if ((not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_enable_reg_pp0_iter3))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_reg_pp0_iter0 <= ap_start;

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_const_logic_0 = ap_start) and (ap_CS_fsm_pp0_stage0 = ap_const_lv1_1) and (ap_const_logic_0 = ap_enable_reg_pp0_iter0) and (ap_const_logic_0 = ap_enable_reg_pp0_iter1) and (ap_const_logic_0 = ap_enable_reg_pp0_iter2) and (ap_const_logic_0 = ap_enable_reg_pp0_iter3))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_phi_precharge_reg_pp0_iter0_g_reg_323 <= "X";
    ap_phi_precharge_reg_pp0_iter1_g_1_reg_336 <= "XX";
    ap_phi_precharge_reg_pp0_iter1_g_2_reg_345 <= "XX";
    ap_phi_precharge_reg_pp0_iter1_g_3_reg_355 <= "XXX";
    ap_phi_precharge_reg_pp0_iter2_g_4_reg_364 <= "XXX";
    ap_phi_precharge_reg_pp0_iter2_g_5_reg_374 <= "XXX";
    ap_phi_precharge_reg_pp0_iter2_g_6_reg_384 <= "XXX";
    ap_phi_precharge_reg_pp0_iter2_p_Val2_1_reg_394 <= "XXXX";

    ap_pipeline_idle_pp0_assign_proc : process(ap_start, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_const_logic_0 = ap_start) and (ap_const_logic_0 = ap_enable_reg_pp0_iter0) and (ap_const_logic_0 = ap_enable_reg_pp0_iter1) and (ap_const_logic_0 = ap_enable_reg_pp0_iter2))) then 
            ap_pipeline_idle_pp0 <= ap_const_logic_1;
        else 
            ap_pipeline_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0)
    begin
        if (((ap_CS_fsm_pp0_stage0 = ap_const_lv1_1) and (ap_const_logic_1 = ap_enable_reg_pp0_iter0) and not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    g_10_fu_628_p2 <= std_logic_vector(unsigned(ap_const_lv3_1) + unsigned(ap_phi_precharge_reg_pp0_iter2_g_3_reg_355));
    g_11_fu_653_p2 <= std_logic_vector(unsigned(ap_const_lv3_1) + unsigned(g_4_phi_fu_367_p4));
    g_12_fu_666_p2 <= std_logic_vector(unsigned(ap_const_lv3_1) + unsigned(g_5_phi_fu_377_p4));
    g_13_fu_689_p2 <= std_logic_vector(unsigned(ap_const_lv4_1) + unsigned(g_6_cast_fu_685_p1));

    g_1_phi_fu_339_p4_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, or_cond1_3_reg_1419, g_7_fu_585_p3, ap_phi_precharge_reg_pp0_iter1_g_1_reg_336, g_cast_fu_580_p1)
    begin
        if (((ap_CS_fsm_pp0_stage0 = ap_const_lv1_1) and (ap_const_logic_1 = ap_enable_reg_pp0_iter1))) then
            if (not((or_cond1_3_reg_1419 = ap_const_lv1_0))) then 
                g_1_phi_fu_339_p4 <= g_cast_fu_580_p1;
            elsif ((or_cond1_3_reg_1419 = ap_const_lv1_0)) then 
                g_1_phi_fu_339_p4 <= g_7_fu_585_p3;
            else 
                g_1_phi_fu_339_p4 <= ap_phi_precharge_reg_pp0_iter1_g_1_reg_336;
            end if;
        else 
            g_1_phi_fu_339_p4 <= ap_phi_precharge_reg_pp0_iter1_g_1_reg_336;
        end if; 
    end process;

    g_2_cast_fu_607_p1 <= std_logic_vector(resize(unsigned(g_2_phi_fu_348_p4),3));

    g_2_phi_fu_348_p4_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, or_cond2_4_reg_1423, g_1_phi_fu_339_p4, g_8_fu_594_p2, ap_phi_precharge_reg_pp0_iter1_g_2_reg_345)
    begin
        if (((ap_CS_fsm_pp0_stage0 = ap_const_lv1_1) and (ap_const_logic_1 = ap_enable_reg_pp0_iter1))) then
            if (not((or_cond2_4_reg_1423 = ap_const_lv1_0))) then 
                g_2_phi_fu_348_p4 <= g_1_phi_fu_339_p4;
            elsif ((or_cond2_4_reg_1423 = ap_const_lv1_0)) then 
                g_2_phi_fu_348_p4 <= g_8_fu_594_p2;
            else 
                g_2_phi_fu_348_p4 <= ap_phi_precharge_reg_pp0_iter1_g_2_reg_345;
            end if;
        else 
            g_2_phi_fu_348_p4 <= ap_phi_precharge_reg_pp0_iter1_g_2_reg_345;
        end if; 
    end process;


    g_4_phi_fu_367_p4_assign_proc : process(ap_enable_reg_pp0_iter2, ap_pipeline_reg_pp0_iter1_or_cond4_6_reg_1431, ap_phi_precharge_reg_pp0_iter2_g_3_reg_355, g_10_fu_628_p2, ap_phi_precharge_reg_pp0_iter2_g_4_reg_364)
    begin
        if ((ap_const_logic_1 = ap_enable_reg_pp0_iter2)) then
            if (not((ap_pipeline_reg_pp0_iter1_or_cond4_6_reg_1431 = ap_const_lv1_0))) then 
                g_4_phi_fu_367_p4 <= ap_phi_precharge_reg_pp0_iter2_g_3_reg_355;
            elsif ((ap_pipeline_reg_pp0_iter1_or_cond4_6_reg_1431 = ap_const_lv1_0)) then 
                g_4_phi_fu_367_p4 <= g_10_fu_628_p2;
            else 
                g_4_phi_fu_367_p4 <= ap_phi_precharge_reg_pp0_iter2_g_4_reg_364;
            end if;
        else 
            g_4_phi_fu_367_p4 <= ap_phi_precharge_reg_pp0_iter2_g_4_reg_364;
        end if; 
    end process;


    g_5_phi_fu_377_p4_assign_proc : process(ap_enable_reg_pp0_iter2, ap_pipeline_reg_pp0_iter1_or_cond5_7_reg_1435, g_11_fu_653_p2, g_4_phi_fu_367_p4, ap_phi_precharge_reg_pp0_iter2_g_5_reg_374)
    begin
        if ((ap_const_logic_1 = ap_enable_reg_pp0_iter2)) then
            if (not((ap_pipeline_reg_pp0_iter1_or_cond5_7_reg_1435 = ap_const_lv1_0))) then 
                g_5_phi_fu_377_p4 <= g_4_phi_fu_367_p4;
            elsif ((ap_pipeline_reg_pp0_iter1_or_cond5_7_reg_1435 = ap_const_lv1_0)) then 
                g_5_phi_fu_377_p4 <= g_11_fu_653_p2;
            else 
                g_5_phi_fu_377_p4 <= ap_phi_precharge_reg_pp0_iter2_g_5_reg_374;
            end if;
        else 
            g_5_phi_fu_377_p4 <= ap_phi_precharge_reg_pp0_iter2_g_5_reg_374;
        end if; 
    end process;

    g_6_cast_fu_685_p1 <= std_logic_vector(resize(unsigned(g_6_phi_fu_387_p4),4));

    g_6_phi_fu_387_p4_assign_proc : process(ap_enable_reg_pp0_iter2, ap_pipeline_reg_pp0_iter1_or_cond6_8_reg_1439, g_12_fu_666_p2, g_5_phi_fu_377_p4, ap_phi_precharge_reg_pp0_iter2_g_6_reg_384)
    begin
        if ((ap_const_logic_1 = ap_enable_reg_pp0_iter2)) then
            if (not((ap_pipeline_reg_pp0_iter1_or_cond6_8_reg_1439 = ap_const_lv1_0))) then 
                g_6_phi_fu_387_p4 <= g_5_phi_fu_377_p4;
            elsif ((ap_pipeline_reg_pp0_iter1_or_cond6_8_reg_1439 = ap_const_lv1_0)) then 
                g_6_phi_fu_387_p4 <= g_12_fu_666_p2;
            else 
                g_6_phi_fu_387_p4 <= ap_phi_precharge_reg_pp0_iter2_g_6_reg_384;
            end if;
        else 
            g_6_phi_fu_387_p4 <= ap_phi_precharge_reg_pp0_iter2_g_6_reg_384;
        end if; 
    end process;

    g_7_fu_585_p3 <= 
        ap_const_lv2_2 when (ap_phi_precharge_reg_pp0_iter1_g_reg_323(0) = '1') else 
        ap_const_lv2_1;
    g_8_fu_594_p2 <= std_logic_vector(unsigned(ap_const_lv2_1) + unsigned(g_1_phi_fu_339_p4));
    g_9_fu_611_p2 <= std_logic_vector(unsigned(ap_const_lv3_1) + unsigned(g_2_cast_fu_607_p1));
    g_cast_fu_580_p1 <= std_logic_vector(resize(unsigned(ap_phi_precharge_reg_pp0_iter1_g_reg_323),2));
    newSel100_cast_fu_1004_p1 <= std_logic_vector(resize(unsigned(newSel4_fu_996_p3),14));
    newSel104_cast_cast_fu_1114_p3 <= 
        ap_const_lv3_3 when (sel_tmp15_fu_1058_p2(0) = '1') else 
        ap_const_lv3_2;
    newSel106_cast_cast_fu_1128_p3 <= 
        ap_const_lv3_1 when (tmp_45_reg_1513(0) = '1') else 
        ap_const_lv3_6;
    newSel10_fu_1310_p3 <= 
        newSel8_fu_1269_p3 when (or_cond7_fu_1277_p2(0) = '1') else 
        newSel9_fu_1283_p3;
    newSel110_cast_fu_1157_p1 <= std_logic_vector(resize(unsigned(newSel7_fu_1149_p3),14));
    newSel116_cast_cast_fu_1297_p3 <= 
        ap_const_lv3_2 when (sel_tmp21_fu_1196_p2(0) = '1') else 
        ap_const_lv3_1;
    newSel11_fu_1324_p3 <= 
        newSel116_cast_cast_fu_1297_p3 when (or_cond9_fu_1305_p2(0) = '1') else 
        ap_const_lv3_7;
    newSel122_cast_fu_1340_p1 <= std_logic_vector(resize(unsigned(newSel12_fu_1332_p3),14));
    newSel12_fu_1332_p3 <= 
        newSel10_fu_1310_p3 when (or_cond10_fu_1318_p2(0) = '1') else 
        newSel11_fu_1324_p3;
    newSel1_fu_867_p3 <= 
        newSel_cast_cast_fu_846_p3 when (or_cond_fu_854_p2(0) = '1') else 
        newSel_fu_860_p3;
    newSel2_fu_955_p3 <= 
        ap_const_lv3_4 when (sel_tmp11_fu_949_p2(0) = '1') else 
        ap_const_lv3_3;
    newSel3_fu_982_p3 <= 
        newSel2_fu_955_p3 when (or_cond1_fu_963_p2(0) = '1') else 
        newSel96_cast_cast_fu_969_p3;
    newSel4_fu_996_p3 <= 
        newSel3_fu_982_p3 when (or_cond3_fu_990_p2(0) = '1') else 
        ap_const_lv3_5;
    newSel5_fu_1100_p3 <= 
        ap_const_lv3_5 when (sel_tmp19_fu_1094_p2(0) = '1') else 
        ap_const_lv3_4;
    newSel6_fu_1135_p3 <= 
        newSel5_fu_1100_p3 when (or_cond4_fu_1108_p2(0) = '1') else 
        newSel104_cast_cast_fu_1114_p3;
    newSel7_fu_1149_p3 <= 
        newSel6_fu_1135_p3 when (or_cond6_fu_1143_p2(0) = '1') else 
        newSel106_cast_cast_fu_1128_p3;
    newSel8_fu_1269_p3 <= 
        ap_const_lv3_6 when (sel_tmp29_fu_1263_p2(0) = '1') else 
        ap_const_lv3_5;
    newSel92_cast_fu_875_p1 <= std_logic_vector(resize(unsigned(newSel1_fu_867_p3),14));
    newSel96_cast_cast_fu_969_p3 <= 
        ap_const_lv3_2 when (sel_tmp7_fu_914_p2(0) = '1') else 
        ap_const_lv3_1;
    newSel9_fu_1283_p3 <= 
        ap_const_lv3_4 when (sel_tmp25_fu_1227_p2(0) = '1') else 
        ap_const_lv3_3;
    newSel_cast_cast_fu_846_p3 <= 
        ap_const_lv3_3 when (sel_tmp3_fu_841_p2(0) = '1') else 
        ap_const_lv3_2;
    newSel_fu_860_p3 <= 
        ap_const_lv3_1 when (tmp_28_reg_1474(0) = '1') else 
        ap_const_lv3_4;
    or_cond10_fu_1318_p2 <= (or_cond7_fu_1277_p2 or or_cond8_fu_1291_p2);
    or_cond1_3_fu_442_p2 <= (tmp_6_fu_430_p2 and tmp_7_fu_436_p2);
    or_cond1_fu_963_p2 <= (sel_tmp11_fu_949_p2 or sel_tmp9_fu_931_p2);
    or_cond2_4_fu_464_p2 <= (tmp_10_fu_452_p2 and tmp_11_fu_458_p2);
    or_cond2_fu_977_p2 <= (sel_tmp7_fu_914_p2 or tmp_36_reg_1499);
    or_cond3_5_fu_486_p2 <= (tmp_17_fu_474_p2 and tmp_18_fu_480_p2);
    or_cond3_fu_990_p2 <= (or_cond1_fu_963_p2 or or_cond2_fu_977_p2);
    or_cond4_6_fu_508_p2 <= (tmp_25_fu_496_p2 and tmp_26_fu_502_p2);
    or_cond4_fu_1108_p2 <= (sel_tmp19_fu_1094_p2 or sel_tmp17_fu_1076_p2);
    or_cond5_7_fu_530_p2 <= (tmp_33_fu_518_p2 and tmp_34_fu_524_p2);
    or_cond5_fu_1122_p2 <= (sel_tmp15_fu_1058_p2 or sel_tmp13_fu_1043_p2);
    or_cond6_8_fu_552_p2 <= (tmp_42_fu_540_p2 and tmp_43_fu_546_p2);
    or_cond6_fu_1143_p2 <= (or_cond4_fu_1108_p2 or or_cond5_fu_1122_p2);
    or_cond7_9_fu_574_p2 <= (tmp_52_fu_562_p2 and tmp_53_fu_568_p2);
    or_cond7_fu_1277_p2 <= (sel_tmp29_fu_1263_p2 or sel_tmp27_fu_1245_p2);
    or_cond8_fu_1291_p2 <= (sel_tmp25_fu_1227_p2 or sel_tmp23_fu_1211_p2);
    or_cond9_fu_1305_p2 <= (sel_tmp21_fu_1196_p2 or tmp_55_reg_1539);
    or_cond_2_fu_420_p2 <= (tmp_1_fu_408_p2 and tmp_2_fu_414_p2);
    or_cond_fu_854_p2 <= (sel_tmp3_fu_841_p2 or sel_tmp6_fu_826_p2);
    p_s_fu_1357_p3 <= 
        ap_const_lv32_0 when (ap_pipeline_reg_pp0_iter2_sync_read_reg_1410(0) = '1') else 
        tmp_62_fu_1351_p2;
    sel_tmp10_demorgan_fu_831_p2 <= (tmp_28_reg_1474 or tmp_30_reg_1481);
    sel_tmp10_fu_943_p2 <= (sel_tmp26_demorgan_fu_937_p2 xor ap_const_lv1_1);
    sel_tmp11_fu_949_p2 <= (tmp_40_fu_904_p2 and sel_tmp10_fu_943_p2);
    sel_tmp12_fu_1038_p2 <= (tmp_45_reg_1513 xor ap_const_lv1_1);
    sel_tmp13_fu_1043_p2 <= (tmp_47_reg_1520 and sel_tmp12_fu_1038_p2);
    sel_tmp14_fu_1052_p2 <= (sel_tmp35_demorgan_fu_1048_p2 xor ap_const_lv1_1);
    sel_tmp15_fu_1058_p2 <= (tmp_48_fu_1023_p2 and sel_tmp14_fu_1052_p2);
    sel_tmp16_fu_1070_p2 <= (sel_tmp42_demorgan_fu_1064_p2 xor ap_const_lv1_1);
    sel_tmp17_fu_1076_p2 <= (tmp_49_fu_1028_p2 and sel_tmp16_fu_1070_p2);
    sel_tmp18_fu_1088_p2 <= (sel_tmp51_demorgan_fu_1082_p2 xor ap_const_lv1_1);
    sel_tmp19_demorgan_fu_920_p2 <= (tmp_36_reg_1499 or tmp_38_fu_894_p2);
    sel_tmp19_fu_1094_p2 <= (tmp_50_fu_1033_p2 and sel_tmp18_fu_1088_p2);
    sel_tmp1_fu_771_p2 <= (ap_pipeline_reg_pp0_iter2_tmp_20_reg_1463 xor ap_const_lv1_1);
    sel_tmp20_fu_1191_p2 <= (tmp_55_reg_1539 xor ap_const_lv1_1);
    sel_tmp21_fu_1196_p2 <= (tmp_57_reg_1546 and sel_tmp20_fu_1191_p2);
    sel_tmp22_fu_1205_p2 <= (sel_tmp60_demorgan_fu_1201_p2 xor ap_const_lv1_1);
    sel_tmp23_fu_1211_p2 <= (tmp_58_reg_1552 and sel_tmp22_fu_1205_p2);
    sel_tmp24_fu_1221_p2 <= (sel_tmp67_demorgan_fu_1216_p2 xor ap_const_lv1_1);
    sel_tmp25_fu_1227_p2 <= (tmp_59_fu_1176_p2 and sel_tmp24_fu_1221_p2);
    sel_tmp26_demorgan_fu_937_p2 <= (sel_tmp19_demorgan_fu_920_p2 or tmp_39_fu_899_p2);
    sel_tmp26_fu_1239_p2 <= (sel_tmp76_demorgan_fu_1233_p2 xor ap_const_lv1_1);
    sel_tmp27_fu_1245_p2 <= (tmp_60_fu_1181_p2 and sel_tmp26_fu_1239_p2);
    sel_tmp28_fu_1257_p2 <= (sel_tmp87_demorgan_fu_1251_p2 xor ap_const_lv1_1);
    sel_tmp29_fu_1263_p2 <= (tmp_61_fu_1186_p2 and sel_tmp28_fu_1257_p2);
    sel_tmp2_fu_776_p2 <= (tmp_22_reg_1469 and sel_tmp1_fu_771_p2);
    sel_tmp35_demorgan_fu_1048_p2 <= (tmp_45_reg_1513 or tmp_47_reg_1520);
    sel_tmp3_fu_841_p2 <= (tmp_31_reg_1487 and sel_tmp_fu_835_p2);
    sel_tmp42_demorgan_fu_1064_p2 <= (sel_tmp35_demorgan_fu_1048_p2 or tmp_48_fu_1023_p2);
    sel_tmp4_fu_909_p2 <= (tmp_36_reg_1499 xor ap_const_lv1_1);
    sel_tmp51_demorgan_fu_1082_p2 <= (sel_tmp42_demorgan_fu_1064_p2 or tmp_49_fu_1028_p2);
    sel_tmp5_fu_821_p2 <= (tmp_28_reg_1474 xor ap_const_lv1_1);
    sel_tmp60_demorgan_fu_1201_p2 <= (tmp_55_reg_1539 or tmp_57_reg_1546);
    sel_tmp67_demorgan_fu_1216_p2 <= (sel_tmp60_demorgan_fu_1201_p2 or tmp_58_reg_1552);
    sel_tmp6_fu_826_p2 <= (tmp_30_reg_1481 and sel_tmp5_fu_821_p2);
    sel_tmp76_demorgan_fu_1233_p2 <= (sel_tmp67_demorgan_fu_1216_p2 or tmp_59_fu_1176_p2);
    sel_tmp7_fu_914_p2 <= (tmp_38_fu_894_p2 and sel_tmp4_fu_909_p2);
    sel_tmp87_demorgan_fu_1251_p2 <= (sel_tmp76_demorgan_fu_1233_p2 or tmp_60_fu_1181_p2);
    sel_tmp8_fu_925_p2 <= (sel_tmp19_demorgan_fu_920_p2 xor ap_const_lv1_1);
    sel_tmp9_fu_931_p2 <= (tmp_39_fu_899_p2 and sel_tmp8_fu_925_p2);
    sel_tmp_fu_835_p2 <= (sel_tmp10_demorgan_fu_831_p2 xor ap_const_lv1_1);
    sel_tmp_v_fu_781_p3 <= 
        ap_const_lv2_2 when (sel_tmp2_fu_776_p2(0) = '1') else 
        ap_const_lv2_1;
    storemerge1_v_cast_c_fu_749_p3 <= 
        ap_const_lv14_1 when (ap_pipeline_reg_pp0_iter2_tmp_14_reg_1447(0) = '1') else 
        ap_const_lv14_2;
    storemerge4_v_cast_fu_802_p1 <= std_logic_vector(resize(unsigned(storemerge4_v_fu_794_p3),14));
    storemerge4_v_fu_794_p3 <= 
        sel_tmp_v_fu_781_p3 when (tmp_23_fu_789_p2(0) = '1') else 
        ap_const_lv2_3;
    t0_V <= count(14 - 1 downto 0);

    t0_V_ap_vld_assign_proc : process(ap_start, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter3, ap_pipeline_reg_pp0_iter2_or_cond_2_reg_1415)
    begin
        if ((not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_enable_reg_pp0_iter3) and (ap_pipeline_reg_pp0_iter2_or_cond_2_reg_1415 = ap_const_lv1_0))) then 
            t0_V_ap_vld <= ap_const_logic_1;
        else 
            t0_V_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    t1_V <= std_logic_vector(unsigned(ap_const_lv14_1) + unsigned(tmp_13_fu_730_p1));

    t1_V_ap_vld_assign_proc : process(ap_start, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter3, ap_pipeline_reg_pp0_iter2_or_cond1_3_reg_1419)
    begin
        if ((not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_enable_reg_pp0_iter3) and (ap_pipeline_reg_pp0_iter2_or_cond1_3_reg_1419 = ap_const_lv1_0))) then 
            t1_V_ap_vld <= ap_const_logic_1;
        else 
            t1_V_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    t2_V <= std_logic_vector(unsigned(storemerge1_v_cast_c_fu_749_p3) + unsigned(tmp_15_fu_745_p1));

    t2_V_ap_vld_assign_proc : process(ap_start, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter3, ap_pipeline_reg_pp0_iter2_or_cond2_4_reg_1423)
    begin
        if ((not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_enable_reg_pp0_iter3) and (ap_pipeline_reg_pp0_iter2_or_cond2_4_reg_1423 = ap_const_lv1_0))) then 
            t2_V_ap_vld <= ap_const_logic_1;
        else 
            t2_V_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    t3_V <= std_logic_vector(unsigned(storemerge4_v_cast_fu_802_p1) + unsigned(tmp_21_fu_767_p1));

    t3_V_ap_vld_assign_proc : process(ap_start, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter3, ap_pipeline_reg_pp0_iter2_or_cond3_5_reg_1427)
    begin
        if ((not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_enable_reg_pp0_iter3) and (ap_pipeline_reg_pp0_iter2_or_cond3_5_reg_1427 = ap_const_lv1_0))) then 
            t3_V_ap_vld <= ap_const_logic_1;
        else 
            t3_V_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    t4_V <= std_logic_vector(unsigned(newSel92_cast_fu_875_p1) + unsigned(tmp_29_fu_817_p1));

    t4_V_ap_vld_assign_proc : process(ap_start, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter3, ap_pipeline_reg_pp0_iter2_or_cond4_6_reg_1431)
    begin
        if ((not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_enable_reg_pp0_iter3) and (ap_pipeline_reg_pp0_iter2_or_cond4_6_reg_1431 = ap_const_lv1_0))) then 
            t4_V_ap_vld <= ap_const_logic_1;
        else 
            t4_V_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    t5_V <= std_logic_vector(unsigned(newSel100_cast_fu_1004_p1) + unsigned(tmp_37_fu_890_p1));

    t5_V_ap_vld_assign_proc : process(ap_start, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter3, ap_pipeline_reg_pp0_iter2_or_cond5_7_reg_1435)
    begin
        if ((not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_enable_reg_pp0_iter3) and (ap_pipeline_reg_pp0_iter2_or_cond5_7_reg_1435 = ap_const_lv1_0))) then 
            t5_V_ap_vld <= ap_const_logic_1;
        else 
            t5_V_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    t6_V <= std_logic_vector(unsigned(newSel110_cast_fu_1157_p1) + unsigned(tmp_46_fu_1019_p1));

    t6_V_ap_vld_assign_proc : process(ap_start, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter3, ap_pipeline_reg_pp0_iter2_or_cond6_8_reg_1439)
    begin
        if ((not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_enable_reg_pp0_iter3) and (ap_pipeline_reg_pp0_iter2_or_cond6_8_reg_1439 = ap_const_lv1_0))) then 
            t6_V_ap_vld <= ap_const_logic_1;
        else 
            t6_V_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    t7_V <= std_logic_vector(unsigned(newSel122_cast_fu_1340_p1) + unsigned(tmp_56_fu_1172_p1));

    t7_V_ap_vld_assign_proc : process(ap_start, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter3, ap_pipeline_reg_pp0_iter2_or_cond7_9_reg_1443)
    begin
        if ((not(((ap_const_logic_1 = ap_enable_reg_pp0_iter0) and (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_enable_reg_pp0_iter3) and (ap_pipeline_reg_pp0_iter2_or_cond7_9_reg_1443 = ap_const_lv1_0))) then 
            t7_V_ap_vld <= ap_const_logic_1;
        else 
            t7_V_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    tmp_10_fu_452_p2 <= "1" when (signed(tmp_9_fu_448_p1) > signed(config_a)) else "0";
    tmp_11_fu_458_p2 <= "1" when (signed(tmp_9_fu_448_p1) < signed(config_b)) else "0";
    tmp_13_fu_730_p1 <= count(14 - 1 downto 0);
    tmp_14_fu_601_p2 <= "1" when (g_1_phi_fu_339_p4 = ap_const_lv2_0) else "0";
    tmp_15_fu_745_p1 <= count(14 - 1 downto 0);
    tmp_16_fu_470_p1 <= std_logic_vector(resize(unsigned(x3_V),32));
    tmp_17_fu_474_p2 <= "1" when (signed(tmp_16_fu_470_p1) > signed(config_a)) else "0";
    tmp_18_fu_480_p2 <= "1" when (signed(tmp_16_fu_470_p1) < signed(config_b)) else "0";
    tmp_1_fu_408_p2 <= "1" when (signed(tmp_fu_404_p1) > signed(config_a)) else "0";
    tmp_20_fu_617_p2 <= "1" when (g_2_phi_fu_348_p4 = ap_const_lv2_0) else "0";
    tmp_21_fu_767_p1 <= count(14 - 1 downto 0);
    tmp_22_fu_623_p2 <= "1" when (g_9_reg_1457 = ap_const_lv3_2) else "0";
    tmp_23_fu_789_p2 <= (sel_tmp2_fu_776_p2 or ap_pipeline_reg_pp0_iter2_tmp_20_reg_1463);
    tmp_24_fu_492_p1 <= std_logic_vector(resize(unsigned(x4_V),32));
    tmp_25_fu_496_p2 <= "1" when (signed(tmp_24_fu_492_p1) > signed(config_a)) else "0";
    tmp_26_fu_502_p2 <= "1" when (signed(tmp_24_fu_492_p1) < signed(config_b)) else "0";
    tmp_28_fu_635_p2 <= "1" when (ap_phi_precharge_reg_pp0_iter2_g_3_reg_355 = ap_const_lv3_0) else "0";
    tmp_29_fu_817_p1 <= count(14 - 1 downto 0);
    tmp_2_fu_414_p2 <= "1" when (signed(tmp_fu_404_p1) < signed(config_b)) else "0";
    tmp_30_fu_641_p2 <= "1" when (g_10_fu_628_p2 = ap_const_lv3_2) else "0";
    tmp_31_fu_647_p2 <= "1" when (g_10_fu_628_p2 = ap_const_lv3_3) else "0";
    tmp_32_fu_514_p1 <= std_logic_vector(resize(unsigned(x5_V),32));
    tmp_33_fu_518_p2 <= "1" when (signed(tmp_32_fu_514_p1) > signed(config_a)) else "0";
    tmp_34_fu_524_p2 <= "1" when (signed(tmp_32_fu_514_p1) < signed(config_b)) else "0";
    tmp_36_fu_660_p2 <= "1" when (g_4_phi_fu_367_p4 = ap_const_lv3_0) else "0";
    tmp_37_fu_890_p1 <= count(14 - 1 downto 0);
    tmp_38_fu_894_p2 <= "1" when (g_11_reg_1492 = ap_const_lv3_2) else "0";
    tmp_39_fu_899_p2 <= "1" when (g_11_reg_1492 = ap_const_lv3_3) else "0";
    tmp_40_fu_904_p2 <= "1" when (g_11_reg_1492 = ap_const_lv3_4) else "0";
    tmp_41_fu_536_p1 <= std_logic_vector(resize(unsigned(x6_V),32));
    tmp_42_fu_540_p2 <= "1" when (signed(tmp_41_fu_536_p1) > signed(config_a)) else "0";
    tmp_43_fu_546_p2 <= "1" when (signed(tmp_41_fu_536_p1) < signed(config_b)) else "0";
    tmp_45_fu_673_p2 <= "1" when (g_5_phi_fu_377_p4 = ap_const_lv3_0) else "0";
    tmp_46_fu_1019_p1 <= count(14 - 1 downto 0);
    tmp_47_fu_679_p2 <= "1" when (g_12_fu_666_p2 = ap_const_lv3_2) else "0";
    tmp_48_fu_1023_p2 <= "1" when (g_12_reg_1506 = ap_const_lv3_3) else "0";
    tmp_49_fu_1028_p2 <= "1" when (g_12_reg_1506 = ap_const_lv3_4) else "0";
    tmp_50_fu_1033_p2 <= "1" when (g_12_reg_1506 = ap_const_lv3_5) else "0";
    tmp_51_fu_558_p1 <= std_logic_vector(resize(unsigned(x7_V),32));
    tmp_52_fu_562_p2 <= "1" when (signed(tmp_51_fu_558_p1) > signed(config_a)) else "0";
    tmp_53_fu_568_p2 <= "1" when (signed(tmp_51_fu_558_p1) < signed(config_b)) else "0";
    tmp_55_fu_695_p2 <= "1" when (g_6_phi_fu_387_p4 = ap_const_lv3_0) else "0";
    tmp_56_fu_1172_p1 <= count(14 - 1 downto 0);
    tmp_57_fu_701_p2 <= "1" when (g_13_fu_689_p2 = ap_const_lv4_2) else "0";
    tmp_58_fu_707_p2 <= "1" when (g_13_fu_689_p2 = ap_const_lv4_3) else "0";
    tmp_59_fu_1176_p2 <= "1" when (g_13_reg_1531 = ap_const_lv4_4) else "0";
    tmp_5_fu_426_p1 <= std_logic_vector(resize(unsigned(x1_V),32));
    tmp_60_fu_1181_p2 <= "1" when (g_13_reg_1531 = ap_const_lv4_5) else "0";
    tmp_61_fu_1186_p2 <= "1" when (g_13_reg_1531 = ap_const_lv4_6) else "0";
    tmp_62_fu_1351_p2 <= std_logic_vector(unsigned(count) + unsigned(ap_const_lv32_8));
    tmp_6_fu_430_p2 <= "1" when (signed(tmp_5_fu_426_p1) > signed(config_a)) else "0";
    tmp_7_fu_436_p2 <= "1" when (signed(tmp_5_fu_426_p1) < signed(config_b)) else "0";
    tmp_9_fu_448_p1 <= std_logic_vector(resize(unsigned(x2_V),32));
    tmp_fu_404_p1 <= std_logic_vector(resize(unsigned(x0_V),32));
    y0_V <= std_logic_vector(resize(unsigned(ap_pipeline_reg_pp0_iter2_x0_V_read_reg_1405),16));
    y1_V <= std_logic_vector(resize(unsigned(ap_pipeline_reg_pp0_iter2_x1_V_read_reg_1400),16));
    y2_V <= std_logic_vector(resize(unsigned(ap_pipeline_reg_pp0_iter2_x2_V_read_reg_1395),16));
    y3_V <= std_logic_vector(resize(unsigned(ap_pipeline_reg_pp0_iter2_x3_V_read_reg_1390),16));
    y4_V <= std_logic_vector(resize(unsigned(ap_pipeline_reg_pp0_iter2_x4_V_read_reg_1385),16));
    y5_V <= std_logic_vector(resize(unsigned(ap_pipeline_reg_pp0_iter2_x5_V_read_reg_1380),16));
    y6_V <= std_logic_vector(resize(unsigned(ap_pipeline_reg_pp0_iter2_x6_V_read_reg_1375),16));
    y7_V <= std_logic_vector(resize(unsigned(ap_pipeline_reg_pp0_iter2_x7_V_read_reg_1370),16));
    yv_V <= ap_phi_precharge_reg_pp0_iter3_p_Val2_1_reg_394;
    iy_V <= (others=>'0');  -- manual addition
end behav;
