## Load configurations
- AmcCarrierCore:
    - AxiVersion:
        - FpgaReloadHalt: !<value> 0x0
        - FpgaReloadAddress: !<value> 0x00000000
        - FpgaReload: !<value> 0x0
        - MasterReset: !<value> 0x0
        - ScratchPad: !<value> 0x00000000
    - AmcCarrierBsa:
        - BsaBufferControl:
            - BsaBuffers:
                - FramesAfterTrigger: !<value> 0x0000
                - MsgDest: !<value> Software
                - SoftTrigger: !<value> 0x0
                - Init: !<value> 0x0
                - Mode: !<value> Wrap
                - Enabled: !<value> 0x0
                - EndAddr: !<value> 0x0000000000000000
                - StartAddr: !<value> 0x0000000000000000
        - BsaWaveformEngine:
            - WaveformEngineBuffers:
                - FramesAfterTrigger: !<value> 0x0000
                - MsgDest: !<value> Auto-Readout
                - SoftTrigger: !<value> 0x0
                - Init: !<value> 0x0
                - Mode: !<value> DoneWhenFull
                - Enabled: !<value>
                    - 0x1
                    - 0x1
                    - 0x1
                    - 0x1
                    - 0x0
                    - 0x0
                    - 0x0
                    - 0x0
                - EndAddr: !<value>
                    - 0x0000000000060000
                    - 0x0000000020060000
                    - 0x0000000040060000
                    - 0x0000000060060000
                    - 0x0000000080060000
                    - 0x00000000a0060000
                    - 0x00000000c0060000
                    - 0x00000000e0060000
                - StartAddr: !<value>
                    - 0x0000000000000000
                    - 0x0000000020000000
                    - 0x0000000040000000
                    - 0x0000000060000000
                    - 0x0000000080000000
                    - 0x00000000a0000000
                    - 0x00000000c0000000
                    - 0x00000000e0000000 
        - TimingFrameRx:
            - MsgDelay: !<value> 0x00000
            - ClkSel: !<value> 0x0
            - RxReset: !<value> 0x0
            - RxPolarity: !<value> 0x0
            - RxCountReset: !<value> 0x0
        - TPGMiniCore:
            - CountInterval: !<value> 0x0000488b
            - BsaAvgToWr: !<value> 0x0000
            - BsaNtoAvg: !<value> 0x0000
            - BsaDestSel: !<value> 0x00000
            - BsaRateSel: !<value> 0x0000
            - BsaCompleteU: !<value> 0x00000000
            - BsaCompleteL: !<value> 0x00000000
            - RateReload: !<value> 0x0
            - FixedRateDiv: !<value>
                - 0x00000001
                - 0x00000000
                - 0x00000000
                - 0x00000000
                - 0x00000000
                - 0x00000000
                - 0x00000000
                - 0x00000000
                - 0x00000000
                - 0x00000000
            - TStampU: !<value> 0x00000000
            - TStampL: !<value> 0x0a5c5b06
            - PulseIdU: !<value> 0x00000000
            - PulseIdL: !<value> 0x0056a6f5
            - BaseControl: !<value> 0x0000
            - TxInhibit: !<value> 0x0
            - TxLoopback: !<value> 0x0
            - TxPolarity: !<value> 0x0
            - TxReset: !<value> 0x0
    - AxiSy56040:
        - OutputConfig: !<value>
            - 0x0
            - 0x3
            - 0x1
            - 0x1
- AppTop:
    - AppCore:
        - AmcGenericAdcDacCore:
            - AmcGenericAdcDacCtrl:
                - CntRst: !<value> 0x0
                - RollOverEn: !<value> 0x0
                - VcoDacSckConfig: !<value> 0xffff
                - LmkMuxSel: !<value> 0x0
                - VcoDacEnable: !<value> 0x1
                - LmkSync: !<value> 0x0
                - LmkRst: !<value> 0x0
                - LmkClkSel: !<value> 0x0
            - Adc16Dx370:
                - AdcReg_0x0070: !<value> 0x22
                - AdcReg_0x0063: !<value> 0x00
                - AdcReg_0x0060: !<value> 0x7d
                - AdcReg_0x0047: !<value> 0x70
                - AdcReg_0x0061: !<value> 0x00
                - AdcReg_0x003D: !<value> 0x00
                - AdcReg_0x003C: !<value> 0x00
                - AdcReg_0x003B: !<value> 0x00
                - AdcReg_0x0019: !<value> 0x00
                - AdcReg_0x0015: !<value> 0x00
                - AdcReg_0x0014: !<value> 0x00
                - AdcReg_0x0013: !<value> 0x40
                - AdcReg_0x0012: !<value> 0x05
                - AdcReg_0x0011: !<value> 0x00
                - AdcReg_0x0010: !<value> 0x03
                - AdcReg_0x000F: !<value> 0x00
                - AdcReg_0x000E: !<value> 0x00
                - AdcReg_0x000D: !<value> 0x04
                - AdcReg_0x000C: !<value> 0x51
                - AdcReg_0x0006: !<value> 0x01
                - AdcReg_0x0005: !<value> 0x00
                - AdcReg_0x0004: !<value> 0x00
                - AdcReg_0x0003: !<value> 0x03
                - AdcReg_0x0002: !<value> 0x00
                - AdcReg_0x0000: !<value> 0x3c
                - AdcReg_0x0062: !<value> 0x01
            - Lmk04828:
                - LmkReg_0x016B: !<value> 0x00
                - LmkReg_0x016C: !<value> 0x00
                - LmkReg_0x016D: !<value> 0xdd
                - LmkReg_0x0173: !<value> 0x00
                - LmkReg_0x0174: !<value> 0x00
                - LmkReg_0x016E: !<value> 0x13
                - LmkReg_0x017C: !<value> 0x15
                - LmkReg_0x017D: !<value> 0x33
                - EnableSysRef: !<value> 0x3
                - EnableSync: !<value> 0xff
                - SyncBit: !<value> 0x0
                - LmkReg_0x016A: !<value> 0x20
                - LmkReg_0x0169: !<value> 0x59
                - LmkReg_0x0168: !<value> 0x70
                - LmkReg_0x0167: !<value> 0x00
                - LmkReg_0x0166: !<value> 0x00
                - LmkReg_0x0165: !<value> 0x0c
                - LmkReg_0x0164: !<value> 0x00
                - LmkReg_0x0162: !<value> 0xf1
                - LmkReg_0x0161: !<value> 0xe0
                - LmkReg_0x0163: !<value> 0x00
                - LmkReg_0x0160: !<value> 0x00
                - LmkReg_0x015F: !<value> 0x0b
                - LmkReg_0x015E: !<value> 0x00
                - LmkReg_0x015D: !<value> 0x00
                - LmkReg_0x015C: !<value> 0x20
                - LmkReg_0x015B: !<value> 0xd4
                - LmkReg_0x015A: !<value> 0xd0
                - LmkReg_0x0159: !<value> 0x07
                - LmkReg_0x0157: !<value> 0x00
                - LmkReg_0x0156: !<value> 0x7d
                - LmkReg_0x0158: !<value> 0x96
                - LmkReg_0x0155: !<value> 0x00
                - LmkReg_0x0154: !<value> 0x78
                - LmkReg_0x0153: !<value> 0x00
                - LmkReg_0x0152: !<value> 0x00
                - LmkReg_0x0151: !<value> 0x02
                - LmkReg_0x0150: !<value> 0x03
                - LmkReg_0x014F: !<value> 0x7f
                - LmkReg_0x014E: !<value> 0x00
                - LmkReg_0x014D: !<value> 0x00
                - LmkReg_0x014C: !<value> 0x00
                - LmkReg_0x014B: !<value> 0x16
                - LmkReg_0x014A: !<value> 0x02
                - LmkReg_0x0149: !<value> 0x02
                - LmkReg_0x0148: !<value> 0x02
                - LmkReg_0x0147: !<value> 0x40
                - LmkReg_0x0146: !<value> 0x18
                - LmkReg_0x0145: !<value> 0x7f
                - LmkReg_0x0143: !<value> 0x51
                - LmkReg_0x0142: !<value> 0x00
                - LmkReg_0x0144: !<value> 0xff
                - LmkReg_0x0141: !<value> 0x00
                - LmkReg_0x0140: !<value> 0x00
                - LmkReg_0x013F: !<value> 0x00
                - LmkReg_0x013E: !<value> 0x03
                - LmkReg_0x013D: !<value> 0x08
                - LmkReg_0x013C: !<value> 0x00
                - LmkReg_0x013B: !<value> 0xe0
                - LmkReg_0x013A: !<value> 0x00
                - LmkReg_0x0139: !<value> 0x03
                - LmkReg_0x0138: !<value> 0x00
                - LmkReg_0x0137: !<value> 0x00
                - LmkReg_0x0136: !<value> 0x78
                - LmkReg_0x0135: !<value> 0x00
                - LmkReg_0x0134: !<value> 0x20
                - LmkReg_0x0133: !<value> 0x00
                - LmkReg_0x0131: !<value> 0x55
                - LmkReg_0x0130: !<value> 0x0e
                - LmkReg_0x012F: !<value> 0x11
                - LmkReg_0x012E: !<value> 0x70
                - LmkReg_0x012D: !<value> 0x00
                - LmkReg_0x012C: !<value> 0x20
                - LmkReg_0x012B: !<value> 0x00
                - LmkReg_0x0129: !<value> 0x55
                - LmkReg_0x0128: !<value> 0x0e
                - LmkReg_0x0127: !<value> 0x00
                - LmkReg_0x0126: !<value> 0x78
                - LmkReg_0x0125: !<value> 0x00
                - LmkReg_0x0124: !<value> 0x20
                - LmkReg_0x0123: !<value> 0x00
                - LmkReg_0x0121: !<value> 0x55
                - LmkReg_0x0120: !<value> 0x0e
                - LmkReg_0x011F: !<value> 0x11
                - LmkReg_0x011E: !<value> 0x70
                - LmkReg_0x011D: !<value> 0x00
                - LmkReg_0x011C: !<value> 0x20
                - LmkReg_0x011B: !<value> 0x00
                - LmkReg_0x0119: !<value> 0x55
                - LmkReg_0x0118: !<value> 0x0e
                - LmkReg_0x0117: !<value> 0x11
                - LmkReg_0x0116: !<value> 0x70
                - LmkReg_0x0115: !<value> 0x00
                - LmkReg_0x0114: !<value> 0x20
                - LmkReg_0x0113: !<value> 0x00
                - LmkReg_0x0111: !<value> 0x55
                - LmkReg_0x0110: !<value> 0x07
                - LmkReg_0x010F: !<value> 0x11
                - LmkReg_0x010E: !<value> 0x70
                - LmkReg_0x010D: !<value> 0x00
                - LmkReg_0x010C: !<value> 0x20
                - LmkReg_0x010B: !<value> 0x00
                - LmkReg_0x0109: !<value> 0x55
                - LmkReg_0x0108: !<value> 0x07
                - LmkReg_0x0107: !<value> 0x11
                - LmkReg_0x0106: !<value> 0x70
                - LmkReg_0x0105: !<value> 0x00
                - LmkReg_0x0104: !<value> 0x20
                - LmkReg_0x0103: !<value> 0x00
                - LmkReg_0x0101: !<value> 0x55
                - LmkReg_0x0100: !<value> 0x07
            - Dac38J84:
                - InitJesd: !<value> 0x01
                - EnableTx: !<value> 0x1
                - DacReg: !<value>
                    - 0x0018
                    - 0x0003
                    - 0x2080
                    - 0xa301
                    - 0xfcfc
                    - 0x000d
                    - 0xfcfc
                    - 0x2a00
                    - 0x0000
                    - 0x0000
                    - 0x0000
                    - 0x0000
                    - 0x0400
                    - 0x0400
                    - 0x0400
                    - 0x0400
                    - 0x0000
                    - 0x0000
                    - 0x0000
                    - 0x0000
                    - 0x0000
                    - 0x0000
                    - 0x0000
                    - 0x0000
                    - 0x0000
                    - 0x0000
                    - 0x0020
                    - 0x0000
                    - 0x0000
                    - 0x0000
                    - 0x9999
                    - 0x9980
                    - 0x8008
                    - 0x0000
                    - 0x1b14
                    - 0xffff
                    - 0x0010
                    - 0x0000
                    - 0x0000
                    - 0x0000
                    - 0x003f
                    - 0xffff
                    - 0x0000
                    - 0x0000
                    - 0x0000
                    - 0x0000
                    - 0xffff
                    - 0x0004
                    - 0x0000
                    - 0x3000
                    - 0x0000
                    - 0x0000
                    - 0x0000
                    - 0x0000
                    - 0x0000
                    - 0x0000
                    - 0x0000
                    - 0x0000
                    - 0x0000
                    - 0x0000
                    - 0x0228
                    - 0x00a8
                    - 0x8908
                    - 0x0000
                    - 0x0000
                    - 0x0000
                    - 0x0000
                    - 0x0000
                    - 0x0000
                    - 0x0000
                    - 0x0044
                    - 0x190a
                    - 0x31c3
                    - 0x0004
                    - 0x0321
                    - 0x0501
                    - 0x1f01
                    - 0x0100
                    - 0x0f0f
                    - 0x1c61
                    - 0x0000
                    - 0x0017
                    - 0x00ff
                    - 0x0000
                    - 0x0017
                    - 0x00ff
                    - 0x0000
                    - 0x00ff
                    - 0x00ff
                    - 0x0000
                    - 0x00ff
                    - 0x00ff
                    - 0x2222
                    - 0x0000
                    - 0x0000
                    - 0x0123
                    - 0x4567
                    - 0x0211
                    - 0x0000
                    - 0x0000
                    - 0x0703
                    - 0x0703
                    - 0xee0b
                    - 0xff07
                    - 0xff07
                    - 0x3f04
                    - 0x9e0f
                    - 0x6d0e
                    - 0x000f
                    - 0xffff
                    - 0x0000
                    - 0x0000
                    - 0x0000
                    - 0x0000
                    - 0x0000
                    - 0x0000
                    - 0x0000
                    - 0x0000
                    - 0x0000
                    - 0x0000
                    - 0x0000
                    - 0x0000
                    - 0x0000
                    - 0x0000
                    - 0x0000
                    - 0x0000
                    - 0x0018
                    - 0x0003
                    - 0x2080
                    - 0xa301
                    - 0xfcfc
                    - 0x000d
                    - 0xfcfc
                    - 0x2a00
                    - 0x0000
                    - 0x0000
                    - 0x0000
                    - 0x0000
                    - 0x0400
                    - 0x0400
                    - 0x0400
                    - 0x0400
                    - 0x0000
                    - 0x0000
                    - 0x0000
                    - 0x0000
                    - 0x0000
                    - 0x0000
                    - 0x0000
                    - 0x0000
                    - 0x0000
                    - 0x0000
                    - 0x0020
                    - 0x0000
                    - 0x0000
                    - 0x0000
                    - 0x9999
                    - 0x9980
                    - 0x8008
                    - 0x0000
                    - 0x1b14
                    - 0xffff
                    - 0x0010
                    - 0x0000
                    - 0x0000
                    - 0x0000
                    - 0x003f
                    - 0xffff
                    - 0x0000
                    - 0x0000
                    - 0x0000
                    - 0x0000
                    - 0xffff
                    - 0x0004
                    - 0x0000
                    - 0x3000
                    - 0x0000
                    - 0x0000
                    - 0x0000
                    - 0x0000
                    - 0x0000
                    - 0x0000
                    - 0x0000
                    - 0x0000
                    - 0x0000
                    - 0x0000
                    - 0x0228
                    - 0x00a8
                    - 0x8908
                    - 0x0000
                    - 0x0000
                    - 0x0000
                    - 0x0000
                    - 0x0000
                    - 0x0000
                    - 0x0000
                    - 0x0044
                    - 0x190a
                    - 0x31c3
                    - 0x0004
                    - 0x0321
                    - 0x0501
                    - 0x1f01
                    - 0x0100
                    - 0x0f0f
                    - 0x1c61
                    - 0x0000
                    - 0x0017
                    - 0x00ff
                    - 0x0000
                    - 0x0017
                    - 0x00ff
                    - 0x0000
                    - 0x00ff
                    - 0x00ff
                    - 0x0000
                    - 0x00ff
                    - 0x00ff
                    - 0x2222
                    - 0x0000
                    - 0x0000
                    - 0x0123
                    - 0x4567
                    - 0x0211
                    - 0x0000
                    - 0x0000
                    - 0x0703
                    - 0x0703
                    - 0xee0b
                    - 0xff07
                    - 0xff07
                    - 0x3f04
                    - 0x9e0f
                    - 0x6d0e
                    - 0x000f
                    - 0xffff
                    - 0x0000
                    - 0x0000
                    - 0x0000
                    - 0x0000
                    - 0x0000
                    - 0x0000
                    - 0x0000
                    - 0x0000
                    - 0x0000
                    - 0x0000
                    - 0x0000
                    - 0x0000
                    - 0x0000
                    - 0x0000
                    - 0x0000
                    - 0x0000
    - AppTopJesd:
        - JesdRx:
            - ScrambleEnable: !<value> Disabled
            - InvertSync: !<value> Regular
            - ClearErrors: !<value> 0x0
            - ResetGTs: !<value> 0x0
            - ReplaceEnable: !<value> Enabled
            - SubClass: !<value> 0x1
            - Enable: !<value> 0x0f
            - SysrefDelay: !<value> 0x0b
        - JesdTx:
            - testOutMux: !<value> SquareWave
            - dataOutMux: !<value> UserData
            - HighAmplitudeVal: !<value> 0x0000ffff
            - LowAmplitudeVal: !<value> 0x00000000
            - SquarePeriod: !<value> 0xffff
            - RampStep: !<value> 0x0001
            - ScrambleEnable: !<value> Disabled
            - ClearErrors: !<value> 0x0
            - InvertSync: !<value> 0x0
            - TestSigEnable: !<value> 0x1
            - ResetGTs: !<value> 0x0
            - Enable: !<value> 0x3
            - ReplaceEnable: !<value> 0x1
            - SubClass: !<value> 0x1    

## Initialize the JESD lanes
- AppTop:            
    - AppTopJesd:
        - JesdRx:
            - ResetRxGTs: !<value> 0x1
        - JesdTx:
            - ResetTxGTs: !<value> 0x1            
    - AppCore:
        - AmcGenericAdcDacCore:
            - InitAmcCard: !<value> 0x1
- AppTop:            
    - AppTopJesd:
        - JesdRx:
            - ResetRxGTs: !<value> 0x1
        - JesdTx:
            - ResetTxGTs: !<value> 0x1            
    - AppCore:
        - AmcGenericAdcDacCore:
            - InitAmcCard: !<value> 0x1            
            
## Initialize the BSA waveform capture engine
- AmcCarrierCore:
    - AmcCarrierBsa:
        - BsaWaveformEngine:
            - WaveformEngineBuffers:   
              - Initialize: !<value> 0x1                 
            